-- Phase 1 catalog-only expansion for marketplace readiness.

ALTER TABLE public.integration_catalog
  ADD COLUMN IF NOT EXISTS auth_type text,
  ADD COLUMN IF NOT EXISTS mcp_server_url text,
  ADD COLUMN IF NOT EXISTS tool_templates jsonb NOT NULL DEFAULT '[]'::jsonb;

INSERT INTO public.integration_catalog (
  code,
  display_name,
  category,
  summary,
  connection_type,
  access_tier,
  rating,
  reviews_count,
  installed_count,
  featured,
  auth_type,
  mcp_server_url,
  tool_templates,
  supported_auth,
  docs_url,
  config_schema,
  is_active
)
VALUES
  ('whatsapp', 'WhatsApp Business', 'Communication', 'Ingest and govern WhatsApp business conversations.', 'webhook', 'pro_plus', 4.60, 18, 390, false, 'oauth2', NULL, '[{"name":"list_conversations","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.facebook.com/docs/whatsapp', '{}'::jsonb, true),
  ('telegram', 'Telegram', 'Communication', 'Index Telegram chats and notifications for operational context.', 'webhook', 'free', 4.40, 14, 280, false, 'bot_token', NULL, '[{"name":"list_updates","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['api_key']::text[], 'https://core.telegram.org/bots/api', '{}'::jsonb, true),
  ('discord', 'Discord', 'Communication', 'Connect Discord channels and events for team intelligence.', 'oauth', 'free', 4.50, 21, 460, false, 'oauth2', NULL, '[{"name":"list_channels","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://discord.com/developers/docs/intro', '{}'::jsonb, true),
  ('microsoft_teams', 'Microsoft Teams', 'Communication', 'Sync Teams chats, channels, and collaboration signals.', 'oauth', 'pro_plus', 4.50, 16, 310, false, 'oauth2', NULL, '[{"name":"list_team_messages","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://learn.microsoft.com/graph/teams-concept-overview', '{}'::jsonb, true),
  ('gmail', 'Gmail', 'Communication', 'Index Gmail threads and route intents with governance.', 'oauth', 'free', 4.70, 35, 860, false, 'oauth2', NULL, '[{"name":"search_threads","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.google.com/gmail/api', '{}'::jsonb, true),
  ('outlook', 'Outlook', 'Communication', 'Sync Outlook mail context for enterprise assistants.', 'oauth', 'free', 4.60, 22, 520, false, 'oauth2', NULL, '[{"name":"search_messages","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://learn.microsoft.com/graph/api/resources/mail-api-overview', '{}'::jsonb, true),
  ('instagram_business', 'Instagram Business', 'Communication', 'Ingest business DMs and comments for support workflows.', 'oauth', 'pro_plus', 4.20, 9, 140, false, 'oauth2', NULL, '[{"name":"list_messages","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.facebook.com/docs/instagram-api', '{}'::jsonb, true),
  ('linkedin', 'LinkedIn', 'Communication', 'Track company posts and engagement signals.', 'oauth', 'enterprise', 4.10, 8, 120, false, 'oauth2', NULL, '[{"name":"list_company_posts","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://learn.microsoft.com/linkedin/', '{}'::jsonb, true),
  ('google_drive', 'Google Drive', 'Documents', 'Index Google Docs/Sheets/Slides and file events.', 'oauth', 'free', 4.80, 38, 970, true, 'oauth2', NULL, '[{"name":"list_files","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.google.com/drive/api', '{}'::jsonb, true),
  ('onedrive', 'OneDrive', 'Documents', 'Ingest OneDrive files and deltas for enterprise search.', 'oauth', 'pro_plus', 4.50, 13, 240, false, 'oauth2', NULL, '[{"name":"list_files","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://learn.microsoft.com/graph/onedrive-concept-overview', '{}'::jsonb, true),
  ('sharepoint', 'SharePoint', 'Documents', 'Bring SharePoint docs and pages into hybrid memory.', 'oauth', 'pro_plus', 4.40, 11, 210, false, 'oauth2', NULL, '[{"name":"search_sites","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://learn.microsoft.com/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index', '{}'::jsonb, true),
  ('confluence', 'Confluence', 'Documents', 'Index Confluence pages, comments, and attachments.', 'oauth', 'pro_plus', 4.50, 25, 540, false, 'oauth2', NULL, '[{"name":"search_pages","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.atlassian.com/cloud/confluence/rest/v2/', '{}'::jsonb, true),
  ('dropbox', 'Dropbox', 'Documents', 'Sync Dropbox files and changes into enterprise context.', 'oauth', 'free', 4.40, 12, 260, false, 'oauth2', NULL, '[{"name":"list_folder","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://www.dropbox.com/developers/documentation/http/documentation', '{}'::jsonb, true),
  ('box', 'Box', 'Documents', 'Enterprise file governance and indexing from Box.', 'oauth', 'pro_plus', 4.30, 10, 190, false, 'oauth2', NULL, '[{"name":"list_items","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.box.com/reference/', '{}'::jsonb, true),
  ('aws_s3', 'Amazon S3', 'Documents', 'Ingest object storage content and notifications.', 'hybrid', 'pro_plus', 4.70, 17, 420, false, 'iam', NULL, '[{"name":"list_objects","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['api_key']::text[], 'https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html', '{}'::jsonb, true),
  ('postgresql', 'PostgreSQL', 'Databases', 'Schema discovery and safe SQL query tooling.', 'hybrid', 'free', 4.90, 46, 1310, true, 'basic_auth', 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres', '[{"name":"query_table","tool_type":"sql_query","risk_level":"medium"}]'::jsonb, ARRAY['basic_auth']::text[], 'https://www.postgresql.org/docs/', '{}'::jsonb, true),
  ('mysql', 'MySQL', 'Databases', 'Schema discovery and read-safe query generation.', 'hybrid', 'free', 4.70, 30, 830, false, 'basic_auth', NULL, '[{"name":"query_table","tool_type":"sql_query","risk_level":"medium"}]'::jsonb, ARRAY['basic_auth']::text[], 'https://dev.mysql.com/doc/', '{}'::jsonb, true),
  ('mongodb', 'MongoDB', 'Databases', 'Collection introspection and aggregate tooling.', 'hybrid', 'free', 4.70, 28, 740, false, 'connection_string', NULL, '[{"name":"find_documents","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['api_key']::text[], 'https://www.mongodb.com/docs/', '{}'::jsonb, true),
  ('redis', 'Redis', 'Databases', 'Realtime keyspace and cache inspection tools.', 'hybrid', 'pro_plus', 4.30, 12, 200, false, 'password', NULL, '[{"name":"get_key","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['basic_auth']::text[], 'https://redis.io/docs/latest/', '{}'::jsonb, true),
  ('supabase', 'Supabase', 'Databases', 'Connect additional Supabase projects and REST tables.', 'oauth', 'free', 4.80, 33, 910, false, 'api_key', NULL, '[{"name":"rest_select","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['api_key']::text[], 'https://supabase.com/docs', '{}'::jsonb, true),
  ('firebase', 'Firebase', 'Databases', 'Firestore and RTDB ingestion for app analytics context.', 'oauth', 'pro_plus', 4.50, 18, 300, false, 'service_account', NULL, '[{"name":"list_documents","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://firebase.google.com/docs', '{}'::jsonb, true),
  ('dynamodb', 'DynamoDB', 'Databases', 'Ingest DynamoDB entities and operational events.', 'hybrid', 'enterprise', 4.20, 8, 140, false, 'iam', NULL, '[{"name":"scan_table","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['api_key']::text[], 'https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/Welcome.html', '{}'::jsonb, true),
  ('salesforce', 'Salesforce', 'CRM', 'Sync leads, opportunities, and account context.', 'oauth', 'pro_plus', 4.80, 42, 1240, true, 'oauth2', NULL, '[{"name":"get_opportunities","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.salesforce.com/docs', '{}'::jsonb, true),
  ('hubspot', 'HubSpot', 'CRM', 'CRM workflows and customer lifecycle intelligence.', 'oauth', 'pro_plus', 4.90, 56, 1420, true, 'oauth2', 'https://developers.hubspot.com/docs/platform/create-an-app', '[{"name":"get_deals","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.hubspot.com/docs', '{}'::jsonb, true),
  ('pipedrive', 'Pipedrive', 'CRM', 'Pipeline health and deal progression analytics.', 'oauth', 'pro_plus', 4.30, 9, 130, false, 'oauth2', NULL, '[{"name":"list_deals","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.pipedrive.com/docs/api/v1/', '{}'::jsonb, true),
  ('zoho_crm', 'Zoho CRM', 'CRM', 'Sales and account telemetry for governed assistants.', 'oauth', 'pro_plus', 4.20, 10, 170, false, 'oauth2', NULL, '[{"name":"list_records","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://www.zoho.com/crm/developer/docs/api/v6/', '{}'::jsonb, true),
  ('jira', 'Jira', 'Project Management', 'Issue, sprint, and workflow intelligence.', 'oauth', 'free', 4.50, 35, 1010, false, 'oauth2', 'https://github.com/modelcontextprotocol/servers/tree/main/src/jira', '[{"name":"list_issues","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2','api_token']::text[], 'https://developer.atlassian.com/cloud/jira/platform/', '{}'::jsonb, true),
  ('asana', 'Asana', 'Project Management', 'Portfolio and task tracking context for ops teams.', 'oauth', 'pro_plus', 4.30, 12, 220, false, 'oauth2', NULL, '[{"name":"list_tasks","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.asana.com/docs', '{}'::jsonb, true),
  ('monday', 'Monday.com', 'Project Management', 'Cross-team workboard context and workload visibility.', 'oauth', 'pro_plus', 4.20, 11, 200, false, 'oauth2', NULL, '[{"name":"list_boards","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.monday.com/api-reference/docs', '{}'::jsonb, true),
  ('linear', 'Linear', 'Project Management', 'Engineering issue context for delivery assistants.', 'oauth', 'pro_plus', 4.40, 14, 260, false, 'oauth2', NULL, '[{"name":"list_issues","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developers.linear.app/docs/graphql/working-with-the-graphql-api', '{}'::jsonb, true),
  ('trello', 'Trello', 'Project Management', 'Board and card context for lightweight workflows.', 'oauth', 'free', 4.10, 8, 130, false, 'oauth2', NULL, '[{"name":"list_cards","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://developer.atlassian.com/cloud/trello/', '{}'::jsonb, true),
  ('sap', 'SAP', 'ERP / Finance', 'ERP finance and inventory operations under governance.', 'oauth', 'enterprise', 4.70, 31, 680, true, 'oauth2', NULL, '[{"name":"get_purchase_orders","tool_type":"http_call","risk_level":"high"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://help.sap.com/', '{}'::jsonb, true),
  ('workday', 'Workday', 'ERP / Finance', 'HR and organizational data analytics connectors.', 'rest_api', 'enterprise', 4.30, 14, 260, false, 'oauth2', NULL, '[{"name":"list_workers","tool_type":"http_call","risk_level":"high"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://developer.workday.com/', '{}'::jsonb, true),
  ('quickbooks', 'QuickBooks', 'ERP / Finance', 'Ledger, invoice, and revenue intelligence integration.', 'oauth', 'pro_plus', 4.60, 19, 470, false, 'oauth2', NULL, '[{"name":"get_profit_and_loss","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.intuit.com/', '{}'::jsonb, true),
  ('xero', 'Xero', 'ERP / Finance', 'Accounting data and statement automation context.', 'oauth', 'pro_plus', 4.20, 9, 140, false, 'oauth2', NULL, '[{"name":"get_invoices","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.xero.com/documentation/api/accounting/overview', '{}'::jsonb, true),
  ('stripe', 'Stripe', 'ERP / Finance', 'Subscription, payment, and invoice signal ingestion.', 'webhook', 'pro_plus', 4.80, 51, 1330, false, 'api_key', 'https://stripe.com/mcp', '[{"name":"get_revenue","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['webhook_secret','api_key']::text[], 'https://docs.stripe.com/api', '{}'::jsonb, true),
  ('razorpay', 'Razorpay', 'ERP / Finance', 'Payment and subscription workflows for India/APAC billing.', 'webhook', 'pro_plus', 4.50, 12, 230, false, 'api_key', NULL, '[{"name":"get_payments","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['api_key','webhook_secret']::text[], 'https://razorpay.com/docs/api/', '{}'::jsonb, true),
  ('github', 'GitHub', 'DevOps / IT', 'PR, issue, and code intelligence connectors.', 'oauth', 'free', 4.90, 68, 2100, true, 'oauth2', 'https://github.com/modelcontextprotocol/servers/tree/main/src/github', '[{"name":"list_pull_requests","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2']::text[], 'https://docs.github.com/en/rest', '{}'::jsonb, true),
  ('gitlab', 'GitLab', 'DevOps / IT', 'Repository and pipeline observability for engineering ops.', 'oauth', 'pro_plus', 4.50, 20, 360, false, 'oauth2', NULL, '[{"name":"list_merge_requests","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://docs.gitlab.com/ee/api/', '{}'::jsonb, true),
  ('servicenow', 'ServiceNow', 'DevOps / IT', 'Incident and change workflow automation context.', 'oauth', 'enterprise', 4.60, 18, 320, false, 'oauth2', NULL, '[{"name":"list_incidents","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['oauth2']::text[], 'https://developer.servicenow.com/dev.do#!/reference/api', '{}'::jsonb, true),
  ('pagerduty', 'PagerDuty', 'DevOps / IT', 'On-call and incident escalation intelligence.', 'oauth', 'pro_plus', 4.40, 15, 280, false, 'oauth2', NULL, '[{"name":"list_incidents","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://developer.pagerduty.com/api-reference/', '{}'::jsonb, true),
  ('datadog', 'Datadog', 'DevOps / IT', 'Monitoring and anomaly telemetry ingestion.', 'rest_api', 'pro_plus', 4.50, 16, 300, false, 'api_key', NULL, '[{"name":"list_monitors","tool_type":"http_call","risk_level":"low"}]'::jsonb, ARRAY['api_key']::text[], 'https://docs.datadoghq.com/api/latest/', '{}'::jsonb, true),
  ('zendesk', 'Zendesk', 'DevOps / IT', 'Support ticket operations and SLA risk context.', 'oauth', 'pro_plus', 4.60, 28, 790, false, 'oauth2', NULL, '[{"name":"list_tickets","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['oauth2','api_key']::text[], 'https://developer.zendesk.com/documentation/', '{}'::jsonb, true),
  ('freshdesk', 'Freshdesk', 'DevOps / IT', 'Ticketing and support workflow context for automation.', 'rest_api', 'pro_plus', 4.30, 11, 220, false, 'api_key', NULL, '[{"name":"list_tickets","tool_type":"http_call","risk_level":"medium"}]'::jsonb, ARRAY['api_key']::text[], 'https://developers.freshdesk.com/api/', '{}'::jsonb, true)
ON CONFLICT (code)
DO UPDATE SET
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  summary = EXCLUDED.summary,
  connection_type = EXCLUDED.connection_type,
  access_tier = EXCLUDED.access_tier,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  installed_count = EXCLUDED.installed_count,
  featured = EXCLUDED.featured,
  auth_type = EXCLUDED.auth_type,
  mcp_server_url = EXCLUDED.mcp_server_url,
  tool_templates = EXCLUDED.tool_templates,
  supported_auth = EXCLUDED.supported_auth,
  docs_url = EXCLUDED.docs_url,
  config_schema = EXCLUDED.config_schema,
  is_active = EXCLUDED.is_active,
  updated_at = now();
